# Name for your GitHub Actions workflow
name: Build and Push Docker Image

# This section defines when the workflow will run
on:
  # Run this workflow every time code is pushed to the 'main' branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-push"
  build-and-push:
    # The type of virtual machine to run the job on
    runs-on: ubuntu-latest

    # A sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Check out your repository code so the workflow can access it
      - name: Check out the repo
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets we stored
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker image and push it to your Docker Hub repository
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/tradevision-app:latest